name: Luxury Homes by The Dealmakers
favicon: null
layout_spectrum: 0.439518399303779
typography_spectrum: 0.6429737391881645
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6824091142043471
  lightness: 0.9131540267262608
  saturation: 0.2276582138147205
  rhythmicContrast: 0.7063310521189123
purpose: []
